### ISSUE TITLE
Missing docs for ReactiveBase

### ISSUE THREAD

**Issue by farhan687** [appbaseio/reactive-manual#6]
- [ ] ReactiveList: new prop `scrollOnTarget` it should be the reference of element or `window` object if user wants to set scroll on window ( https://github.com/appbaseio/reactivebase/issues/104 )

- [x] Support `weights` prop in `datasearch` and in `categorysearch` (https://github.com/appbaseio/reactivebase/issues/107)
weights can be used to set the weights of fileds.
It should be an array and should be in same order of appbaseField.

- [x] Pagination new prop: `pages`  (https://github.com/appbaseio/reactivebase/issues/111)
  Implement pages prop to change size of shown pages.
